name: Check and Update .env.example on PR

on:
  pull_request:
    branches:
      - master

jobs:
  check-update-env-example:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "erdemkosk@gmail.com"
          git config --global user.name "Erdem Köşk"

      - name: Check out code
        uses: actions/checkout@v2  # GitHub Actions'ın önceden tanımlanmış bir eylemi

      - name: Get Current Directory
        run: |
          current_directory=$(pwd)
          echo "Current Directory: $current_directory"
          
          # Değişiklikleri çek ve .env.example dosyasını güncelle
          git -C "$current_directory" fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git -C "$current_directory" checkout ${{ github.event.pull_request.head.ref }}

          # .env.example dosyasını kontrol et veya oluştur
          if [ ! -f "$current_directory/.env.example" ]; then
            touch "$current_directory/.env.example"
          fi

          # .env.example dosyasının içeriğini al
          env_example_content=$(<"$current_directory/.env.example")

          # PR içeriğini çek
          pr_diff=$(git -C "$current_directory" diff --name-only HEAD^)

          # PR içeriğindeki dosyaları işle
          for file in $pr_diff; do
            # Dosya içeriğini kontrol et
            file_content=$(<"$current_directory/$file")

            # Dosya içeriğindeki process.env değerlerini bul
            process_env_values=$(echo "$file_content" | grep -Eo 'process\.env\.[A-Za-z_][A-Za-z_0-9]*')

            # Her bir process.env değerini kontrol et
            for value in $process_env_values; do
              # Değer .env.example dosyasında eksikse veya farklısa, .env.example dosyasını ekler veya günceller
              if [[ ! $env_example_content == *"$value"* ]]; then
                # Değerin başka bir değerle değiştirilip değiştirilmediğini kontrol et
                if [[ $env_example_content == *"$value"* ]]; then
                  # Değer aynı, bu yüzden güncelleme yapmaya gerek yok
                  continue
                fi
                # Değeri .env.example dosyasına ekler veya günceller
                sed -i "/$value/c$value=<default_value>" "$current_directory/.env.example"
                git -C "$current_directory" add "$current_directory/.env.example"
                git -C "$current_directory" commit -m "Update $value in .env.example"
                git -C "$current_directory" push origin ${{ github.event.pull_request.head.ref }}
              fi
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
